config/routes.rb
Beauty::Application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'login',  to: 'users/sessions#new',     as: :new_user_session
    get 'logout', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  root to: 'main#index'

  resources :companies
  scope 'employees' do
    match ':id/allow' => 'employees#allow', as: :allow_employee, via: :put
    match ':id/ban'   => 'employees#ban',   as: :ban_employee,   via: :delete
  end
  resources :employees
end

app/models/company.rb
class Company < ActiveRecord::Base
  extend FriendlyId
  friendly_id :brand, use: :slugged

  belongs_to :employer
  has_many   :employees

  mount_uploader  :logo, LogoUploader

  attr_accessible :logo, :logo_cache, :remote_logo_url, :brand, :address, :phone, :email

  validates :brand,        presence: true, :uniqueness => true
  validates :address,      presence: true
  validates :phone,        presence: true, format: /\A\+?[0-9\s\-\(\)]+\z/
  validates :email,        presence: true, email: true

  acts_as_gmappable lat:               'lat',
                    lng:               'lng',
                    process_geocoding: :geocode?,
                    address: 'address',
                    normalized_address: 'address',
                    callback:           :customize_address,
                    msg: 'Sorry, not even Google could figure out where that is'

  def location
    data = []
    data.push(self.country) if self.country.present?
    data.push(self.state + ' area')   if self.state.present?
    data.push(self.city)    if self.city.present?

    data.empty? ? false : data.join(', ')
  end

  protected

  def geocode?
    (!address.blank? && (lat.blank? || lng.blank?)) || address_changed?
  end

  def customize_address(data)
    data['address_components'].each do |c|
      if c['types'].include? 'country'
        self.country = c['long_name']
      elsif c['types'].include? 'locality'
        self.city = c['long_name']
      elsif c['types'].include? 'administrative_area_level_1'
        self.state = c['long_name']
      end
    end
  end
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :user
  belongs_to :company

  attr_accessible :role, :company_id

  validates :company_id, presence: true

  scope :allowed, where(allowed: true)

  def allow!
    self.allowed = true
    save!
  end

  def ban!
    self.allowed = false
    save!
  end

  def splitted_role
    return self.role.split(',').map(&:strip) if self.role.present?
    []
  end
end

app/models/employer.rb
class Employer < ActiveRecord::Base
  belongs_to :user
  has_many   :companies
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :name, :logo, :link, :gender

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :encryptable, :omniauthable

  attr_accessible :username, :provider, :uid, :access_token, :email

  @graph = false

  has_one  :profile
  has_one  :employer
  has_many :employees

  validates :email,              presence: true, uniqueness: true
  validates :username,           presence: true, uniqueness: true
  validates :uid,                presence: true, :uniqueness => { scope: [:provider] }
  validates :provider,           presence: true
  validates :encrypted_password, presence: true
  validates :password_salt,      presence: true

  def graph
    @fb_graph || @fb_graph = Koala::Facebook::API.new(self.access_token)
  end

  def puts_to_feed(message=nil)
    graph.put_connections('me', 'feed', message: message) if message.present?
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first
    user_hash = {
        username:     auth.extra.raw_info.username,
        provider:     auth.provider,
        uid:          auth.uid,
        access_token: auth.credentials.token,
        email:        auth.extra.raw_info.email
    }
    profile_hash = {
        name:   auth.extra.raw_info.name,
        logo:   auth.info.image,
        link:   auth.extra.raw_info.link,
        gender: auth.extra.raw_info.gender
    }
    unless user
      user = User.new(user_hash)
      user.password = Devise.friendly_token[4,20]
      user.build_profile(profile_hash)
      user.save
    else
      user.update_attributes(user_hash)
      user.profile.update_attributes(profile_hash) if user.profile.present?
    end
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :fetch_company, only: [:edit, :update, :destroy]

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(params[:company])

    if @company.valid?
      @company.employer = current_user.employer || current_user.create_employer
      @company.save!

      flash[:notice] = 'New company has been successfully saved.'
      redirect_to company_path(@company)
    else
      render :new
    end
  end

  def show
    @company = Company.find(params[:id])
    if @company.present?
      @owner = @company.employer.user == current_user
      @employees = @owner ? @company.employees.all : @company.employees.allowed.all
    end
  end

  def edit
  end

  def update
    if @company.update_attributes(params[:company])
      flash[:notice] = 'Company has been successfully updated.'
      redirect_to company_path(@company)
    else
      render :edit
    end
  end

  def destroy
    if @company.destroy
      flash[:notice] = 'Company has been successdully deleted.'
    end
    redirect_to root_path
  end

  protected

  def fetch_company
    @company = Company.find(params[:id])
    not_found unless @company.employer.user == current_user
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :fetch_employee, only: [:edit, :update, :destroy]

  def new
    @employee = current_user.employees.build
  end

  def create
    @employee = current_user.employees.build(params[:employee])
    if @employee.save
      flash[:notice] = 'New employee has been successfully saved.'
      redirect_to company_path(@employee.company)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @employee.update_attributes(params[:employee])
      flash[:notice] = 'Employee has been successfully updated.'
      redirect_to company_path(@employee.company)
    else
      render :edit
    end
  end

  def destroy
    if @employee.destroy
      flash[:notice] = 'Employee has been successfully deleted.'
    end
    redirect_to root_path
  end

  def allow
    @employee = Employee.find(params[:id])
    unless @employee.company.employer.user == current_user
      not_found
    else
      @employee.allow!
      flash[:notice] = 'Employee has been successfully allowed.'
      redirect_to company_path(@employee.company)
    end
  end

  def ban
    @employee = Employee.find(params[:id])
    unless @employee.company.employer.user == current_user
      not_found
    else
      @employee.ban!
      flash[:notice] = 'Employee has been successfully banned.'
      redirect_to company_path(@employee.company)
    end
  end

  protected

  def fetch_employee
    @employee = Employee.find(params[:id])
    not_found unless @employee.user == current_user || @employee.company.employer.user == current_user
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env['omniauth.auth'], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to 'http://apps.facebook.com/beauty-register/'
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new
    redirect_to user_omniauth_authorize_path(:facebook)
  end

  def create
    super
  end

  def destroy
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/companies/_form.html.haml
= simple_form_for(@company, :html => { class: 'form-horizontal', autocomplete: 'off', multipart: true }) do |f|
  %fieldset
    %legend
      - unless @company.new_record?
        = link_to 'Delete', company_path(@company), class: 'btn btn-small btn-danger pull-right', method: :delete, :data => { confirm: 'Are you sure?' }
      %h4= @company.new_record? ? 'New Company' : 'Edit Company'
    - if @company.logo.present?
      .controls
        = link_to 'Delete?', '#', id: 'delete_company_logo'
        = image_tag @company.logo.url, class: 'thumbnail'
        %br/
    = f.input :logo  do
      = f.file_field :logo, style: 'display:none;'
      %input{ type: 'text', id: 'company_logo_cover',
        value: @company.logo_cache.present? ? File.basename(@company.logo_cache) : '' }
      %a{ class: 'btn', id: 'company_logo_cover_btn' } Browse
      %br/
      or download from:
      %br/
      = f.text_field :remote_logo_url, placeholder: 'http://'
    = f.input :logo_cache, as: :hidden
    = f.input :brand, autofocus: true
    = f.input :address
    = f.input :email
    = f.input :phone

    .form-actions
      = f.submit 'Save', class: 'btn btn-success btn-large'
      = ' or '
      %button.btn.btn-large.reset_state_code{ type: 'reset' } Reset

app/views/companies/edit.html.haml
#edit-company-form-container.span8= render 'form'

app/views/companies/new.html.haml
#new-company-form-container.span8= render 'form'

app/views/companies/show.html.haml
- if @owner
  .company-management-top-panel.pull-right
    = link_to 'Edit', edit_company_path(@company), class: 'btn btn-large btn-success'
.company-content-container
  .row#company-head
    %h2
      .row-fluid
        .span1
          = image_tag @company.logo.url, class: 'thumbnail pull-right' if @company.logo.present?
        .span8
          = @company.brand.titleize
          - if @company.location
            %br/
            %span.label.label-success= @company.location
  .row#company-body
    - owner_profile = @company.employer.user.profile
    .row-fluid#owner-info
      .span1
        = image_tag owner_profile.logo, class: 'thumbnail pull-right', width: '25' if owner_profile.logo.present?
      .span2= link_to owner_profile.name.titleize, owner_profile.link, target: '_blank'
      .span9
        = "Register this company #{time_ago_in_words(@company.created_at)} ago"
        - unless @company.updated_at == @company.created_at
          %br/
          = "Latest updates are made #{time_ago_in_words(@company.updated_at)} ago"
    .row-fluid#contact-info.well.span11
      %h4 Contact information:
      %br/
      .span3
        .row-fluid
          .span4
            %span.label.label-info Email:
          .span4= mail_to @company.email.downcase
        .row-fluid
          .span4
            %span.label.label-info Phone:
          .span4= @company.phone
        .row-fluid
          .span4
            %span.label.label-info Address:
          .span4
            = link_to @company.address, "http://www.google.com/maps?q=#{@company.address}", target: '_blank'
      .span8
        #company-map
          = gmaps('markers' => { data: @company.to_gmaps4rails },
                  'map_options' => { 'auto_zoom' => false, 'zoom' => 15})
    .row#employees-container.well.span11
      %h4 Employees:
      %br/
      - @employees.each do |employee|
        - profile = employee.user.profile
        .row-fluid
          .span1
            = image_tag profile.logo, class: 'thumbnail' if profile.logo.present?
          .span6
            = link_to profile.link, target: '_blank' do
              %h4= profile.name.titleize
            - employee.splitted_role.each do |role|
              %span.label.label-success= role.capitalize
          .span3
          - if @owner || employee.user == current_user
            = link_to 'Edit', edit_employee_path(employee), class: 'btn btn-large'
            - if @owner and !employee.allowed?
              = link_to 'Allow', allow_employee_path(employee), class: 'btn btn-large btn-success', method: :put, data: { confirm: 'Are you sure?' }
            - elsif @owner and employee.allowed?
              = link_to 'Ban', ban_employee_path(employee), class: 'btn btn-large btn-danger', method: :delete, data: { confirm: 'Are you sure?' }

app/views/employees/_form.html.haml
= simple_form_for @employee, :html => { class: 'form-horizontal', autocomplete: 'off' } do |f|
  %fieldset
    %legend
      - unless @employee.new_record?
        = link_to 'Delete', employee_path(@employee), class: 'btn btn-small btn-danger pull-right', method: :delete, :data => { confirm: 'Are you sure?' }
      %h4= @employee.new_record? ? 'New Employee' : 'Edit Employee'

    = f.association :company, label_method: :brand, prompt: 'Choose a company'
    = f.input :role, autofocus: true, placeholder: 'Men\'s grooming, body care ...'

    .form-actions
      = f.submit 'Save', class: 'btn btn-success btn-large'
      = ' or '
      %button.btn.btn-large.reset_state_code{ type: 'reset' } Reset

app/views/employees/edit.html.haml
#edit-employee-form-container.span8= render 'form'

app/views/employees/new.html.haml
#new-employee-form-container.span8= render 'form'

app/views/layouts/_flashes.html.haml
- flash.each do |key, value|
  %div{ :class => "alert alert-#{key == :notice ? 'success' : 'error'}" }= value

app/views/layouts/_footer.html.haml
.navbar-fixed-bottom
  .navbar-inner
    .container-fluid
      .navbar
        %ul.nav.pull-right
          %li
            = link_to root_path do
              = raw "&copy; We &hearts; Customers. #{Time.current.year}"

app/views/layouts/_header.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container-fluid
      %a.brand(href=root_path)= raw '{ Beauty Register&reg; }'
      be free
      %ul.nav.pull-right
        - unless user_signed_in?
          = link_to 'Log in', user_omniauth_authorize_path(:facebook), class: 'btn btn-success btn-large', style: 'margin-top:1px;'
        - else
          = link_to 'Log out', destroy_user_session_path, :data => { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-small',
            style: 'margin-top:7px;'

app/views/layouts/_nav_list.html.haml
%ul.nav.nav-list
  %li.nav-header For Customers:
  %li.nav-header For Employers:
  = link_to 'Register a new company', new_company_path, class: 'btn btn-success'
  - if current_user.present? and (employer = current_user.employer).present?
    - if employer.companies.present?
      %li.divider
    - employer.companies.each do |company|
      %li
        = link_to company_path(company) do
          .row-fluid
            .span2.thumbnail
              = image_tag company.logo.url, width: '25' if company.logo.present?
            .span10= company.brand.titleize
  %li.divider
  = link_to 'Register as an employee', new_employee_path, class: 'btn'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : 'Beauty Register'
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"

  %body
    = render 'layouts/header'
    .container-fluid
      .row-fluid
        .span3
          = render 'layouts/nav_list'
        .span9
          = render 'layouts/flashes'
          = yield
    = render 'layouts/footer'

    = javascript_include_tag "application"
    = yield(:scripts)

app/views/shared/_back.html.haml
.back-container
  = link_to raw("&#9668; Go back"), :back, class: 'pull-left'